### PR TITLE
Use encryption params passed to dispatcher in negative consensus case.

### LINKED ISSUE #364: NegativeConsensus do not use encryptionParameters
When giving a negative consensus in the `direct_post.jwt` response mode, the SDK fails with a message: "_Diffie-Hellman encryption parameters are required for ECDH-ES_". The message comes from `JarmJwt.kt` and `jweHeader` function.

The main problem is probably in the `AuthorizationResponse.kt` file, where `ResolvedRequestObject.responsePayload` has `EncryptionParameters` as an optional parameter, but never uses it for the negative consensus.

The quick fix should be to add it into `NoConsensusResponseData` as:
```
private fun ResolvedRequestObject.responsePayload(
    consensus: Consensus,
    encryptionParameters: EncryptionParameters?,
): AuthorizationResponsePayload = when (consensus) {
    is Consensus.NegativeConsensus -> AuthorizationResponsePayload.NoConsensusResponseData(nonce, state, client.id, encryptionParameters)
...
```

### PR DESCRIPTION
**Pull request by vafeini**
Closes #364

### CODE REVIEW

**Review by dzarras — DISMISSED** [review]

File: src/main/kotlin/eu/europa/ec/eudi/openid4vp/ResponseDispatcher.kt [hunk 1]
```diff
@@ -131,11 +131,11 @@ interface Dispatcher {
         encryptionParameters: EncryptionParameters?,
     ): DispatchOutcome =
         when (request.responseMode) {
-            is ResponseMode.DirectPost -> post(request, consensus, encryptionParameters)
+            is ResponseMode.DirectPost -> post(request, consensus)
```
Comment (babisRoutis) [inline src/main/kotlin/eu/europa/ec/eudi/openid4vp/ResponseDispatcher.kt:134]: Consider passing explicitly `null`

**Review by babisRoutis — DISMISSED** [review]
@vafeini Just a single, very minor, comment.

File: src/main/kotlin/eu/europa/ec/eudi/openid4vp/ResponseDispatcher.kt (hunk 1 above)
Comment (vafeini) [reply src/main/kotlin/eu/europa/ec/eudi/openid4vp/ResponseDispatcher.kt]: done
